#!/bin/bash

echo -n "Checking bundle... "
if $(bundle check &> /dev/null); then
  echo "OK 👍"
else
  echo "failed! 💥"
  echo "Updating bundle..."
  bundle install --jobs 20 --retry 5 --clean
fi

exec "$@"
