#!/bin/sh

# Skip this entrypoint if `DISABLE_AUTO_INSTALL_DEPS` is set
if [ "${DISABLE_AUTO_INSTALL_DEPS}" = "1" ]; then
  exec "$@"
  exit 0
fi

if [ -f Gemfile ]; then
  echo -n "Checking bundle... "
  if $(bundle check &> /dev/null); then
    echo "all good 👌"
  else
    echo "Something is missing 💥"
    echo "Updating bundle now…"
    BUNDLE_CLEAN=true bundle install --jobs 20 --retry 5
  fi
else
  echo "No Gemfile found. Skipping Ruby dependencies check."
fi

exec "$@"
