#!/bin/bash

export APP_USER_NAME="user"

if ! grep -q "^${APP_USER_NAME}:" /etc/group; then
  groupadd                           \
    --gid $(stat --format '%g' /app) \
    --non-unique                     \
    ${APP_USER_NAME} &> /dev/null
fi

if ! grep -q "^${APP_USER_NAME}:" /etc/passwd; then
  useradd                            \
    --shell "/bin/bash"              \
    --uid $(stat --format '%u' /app) \
    --gid $(stat --format '%g' /app) \
    --no-user-group                  \
    --comment "Docker Ruby dev <3"   \
    --non-unique                     \
    --create-home                    \
    ${APP_USER_NAME} &> /dev/null
fi

node_modules_path=$(grep node_modules /etc/mtab | cut -d' ' -f2)

chown --silent --recursive ${APP_USER_NAME}:${APP_USER_NAME} \
  /bundle                                                    \
  /config                                                    \
  ${node_modules_path}

gosu ${APP_USER_NAME} "$@"
