#!/bin/sh

if ! mountpoint -q /app; then
  exec "$@"
  exit 0
fi

export APP_USER_NAME="user"
export APP_USER_UID="${GOSU_FORCE_UID:-$(stat -c '%u' /app)}"
export APP_USER_GID="${GOSU_FORCE_GID:-$(stat -c '%g' /app)}"

if ! grep -q "^${APP_USER_NAME}:" /etc/group; then

  # Create group
  case "$(sed -n 's|^ID=||p' /etc/os-release)" in
    alpine)
      addgroup -g ${APP_USER_GID} ${APP_USER_NAME}
    ;;
    debian|ubuntu)
      groupadd \
        --gid ${APP_USER_GID} \
        --non-unique \
        ${APP_USER_NAME}
    ;;
  esac
fi

if ! grep -q "^${APP_USER_NAME}:" /etc/passwd; then

  # Create user
  case "$(sed -n 's|^ID=||p' /etc/os-release)" in
    alpine)
      adduser -D -u ${APP_USER_UID} -G ${APP_USER_NAME} ${APP_USER_NAME}
    ;;
    debian|ubuntu)
      useradd \
        --shell "/bin/bash" \
        --uid ${APP_USER_UID} \
        --gid ${APP_USER_GID} \
        --no-user-group \
        --non-unique \
        --create-home \
        ${APP_USER_NAME}
    ;;
  esac
fi

eval ${GOSU_PRE_CHOWN_CMD}

node_modules_mountpoint=$(grep node_modules /etc/mtab | cut -d' ' -f2)

# Change ownership (this may take a few seconds, but only the first time)
chown -Rf ${APP_USER_NAME}:${APP_USER_NAME} \
  /bundle \
  /config \
  ${node_modules_mountpoint} \
  ${GOSU_ADDITIONAL_CHOWN_TARGETS}

gosu ${APP_USER_NAME} "$@"
