#!/bin/sh

# Remove rails server PID file, that is sometimes not properly removed at shutdown
# as instructed in https://docs.docker.com/compose/rails/
rm -f /app/${RELATIVE_RAILS_ROOT}/tmp/pids/server.pid

exec "$@"
