#!/bin/sh

# Skip this entrypoint if `DISABLE_AUTO_INSTALL_DEPS` is set
if [ "${DISABLE_AUTO_INSTALL_DEPS}" = "1" ]; then
  exec "$@"
  exit 0
fi

if [ -f package.json ]; then
  check_command=$( \
    yarn run 2> /dev/null | grep -qx '^\s\+-\s\+check$' \
      && echo "yarn run --silent check" \
      || echo "yarn check --integrity --verify-tree --silent" \
  )
  echo -n "Checking JS modules... "
  if eval ${check_command} 2> /dev/null; then
    echo "all good 👌"
  else
    echo "something is missing 💥"
    echo "Updating JS modules now…"
    yarn install --check-files --frozen-lockfile
  fi
else
  echo "No package.json found. Skipping JS dependencies check."
fi

exec "$@"
