name: Docker Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: alpinelab/ruby-dev:${{ matrix.ruby }}${{ matrix.variant }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.4.2
          - 3.4.1
          # Ruby 3.4.0 never existed: it was mis-packaged and 3.4.1 was released immediately to fix it
          - 3.3.8
          - 3.3.7
          - 3.3.6
          - 3.3.5
          - 3.3.4
          - 3.3.3
          - 3.3.2
          - 3.3.1
          - 3.3.0
          - 3.2.8
          - 3.2.7
          - 3.2.6
          - 3.2.5
          - 3.2.4
          - 3.2.3
          - 3.2.2
          - 3.2.1
          - 3.2.0
          - 3.1.7
          - 3.1.6
          - 3.1.5
          - 3.1.4
          - 3.1.3
          - 3.1.2
          - 3.1.1
          - 3.1.0
          - 3.0.7
          - 3.0.6
          - 3.0.5
          - 3.0.4
          - 3.0.3
          - 3.0.2
          - 3.0.1
          - 3.0.0
          - 2.7.8
          - 2.7.7
          - 2.7.6
          - 2.7.5
          - 2.7.4
          - 2.7.3
          - 2.7.2
          - 2.7.1
          - 2.7.0
          - 2.6.10
          - 2.6.9
          - 2.6.8
          - 2.6.7
          - 2.6.6
          - 2.6.5
          - 2.6.4
          - 2.6.3
          - 2.5.9
          - 2.5.8
          - 2.5.7
          - 2.5.6
          - 2.5.5
          - 2.4.10
          - 2.4.9
          - 2.4.8
          - 2.4.7
          - 2.4.6
        variant: ["", "-alpine"]

    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        push: true
        build-args: |
          BASE_IMAGE_TAG=${{ matrix.ruby }}${{ matrix.variant }}

          ${{ startsWith(matrix.ruby, '3.0') && 'RUBYGEMS_VERSION_ARG=3.5.23' || '' }}
          ${{ startsWith(matrix.ruby, '2.7') && 'RUBYGEMS_VERSION_ARG=3.4.22' || '' }}
          ${{ startsWith(matrix.ruby, '2.6') && 'RUBYGEMS_VERSION_ARG=3.4.22' || '' }}
          ${{ startsWith(matrix.ruby, '2.5') && 'RUBYGEMS_VERSION_ARG=3.3.26' || '' }}
          ${{ startsWith(matrix.ruby, '2.4') && 'RUBYGEMS_VERSION_ARG=3.3.26' || '' }}

          ${{ startsWith(matrix.ruby, '3.0') && 'BUNDLER_VERSION_ARG=2.5.23' || '' }}
          ${{ startsWith(matrix.ruby, '2.7') && 'BUNDLER_VERSION_ARG=2.4.22' || '' }}
          ${{ startsWith(matrix.ruby, '2.6') && 'BUNDLER_VERSION_ARG=2.4.22' || '' }}
          ${{ startsWith(matrix.ruby, '2.5') && 'BUNDLER_VERSION_ARG=2.3.26' || '' }}
          ${{ startsWith(matrix.ruby, '2.4') && 'BUNDLER_VERSION_ARG=2.3.26' || '' }}

        tags: |
          alpinelab/ruby-dev:${{ matrix.ruby }}${{ matrix.variant }}

          ${{ matrix.ruby == '3.4.2' && format('alpinelab/ruby-dev:latest{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '3.4.2' && format('alpinelab/ruby-dev:3{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '3.4.2' && format('alpinelab/ruby-dev:3.4{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '3.3.8' && format('alpinelab/ruby-dev:3.3{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '3.2.8' && format('alpinelab/ruby-dev:3.2{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '3.1.7' && format('alpinelab/ruby-dev:3.1{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '3.0.7' && format('alpinelab/ruby-dev:3.0{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '2.7.8' && format('alpinelab/ruby-dev:2.7{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '2.7.8' && format('alpinelab/ruby-dev:2{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '2.6.10' && format('alpinelab/ruby-dev:2.6{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '2.5.9' && format('alpinelab/ruby-dev:2.5{0}', matrix.variant) || '' }}
          ${{ matrix.ruby == '2.4.10' && format('alpinelab/ruby-dev:2.4{0}', matrix.variant) || '' }}

        cache-from: type=gha
        cache-to: type=gha,mode=max
